services:
  # Serviço do Backend (API FastAPI)
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/.env:/app/.env
      
      - ./backend/data:/app/data
      
      - ./backend/chroma_db:/app/chroma_db
      
    container_name: myagent-backend

  # Serviço do Frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    container_name: myagent-frontend