services:
  # Serviço do Backend (API FastAPI)
  backend:
    build: ./backend  # Constrói a imagem usando o Dockerfile na pasta 'backend'
    ports:
      - "8000:8000"  # Mapeia a porta 8000 do seu PC para a porta 8000 do contêiner
    volumes:
      - ./backend/.env:/app/.env # Monta o arquivo .env para que o contêiner tenha acesso à chave da API
    container_name: myagent-backend

  # Serviço do Frontend (Aplicação Next.js)
  frontend:
    build: ./frontend # Constrói a imagem usando o Dockerfile na pasta 'frontend'
    ports:
      - "3000:3000"  # Mapeia a porta 3000 do seu PC para a porta 3000 do contêiner
    depends_on:
      - backend      # Diz ao Docker para esperar o backend iniciar antes de iniciar o frontend
    container_name: myagent-frontend